// SEO content — geographic + Australian building knowledge.
// Contains no Apollo Builders-specific claims (no project counts, awards, etc.).
// Every fact is verifiable via VicPlan, council pages, or general construction knowledge.

export const suburbData = {
  brighton: {
    name: "Brighton", state: "VIC", postcode: "3186",
    council: "Bayside City Council",
    zone: "Predominantly General Residential Zone; some Neighbourhood Residential Zone pockets",
    profile: "Brighton is a bayside suburb 11 km south-east of Melbourne CBD known for its coastline, Church Street shopping strip and the iconic Brighton bathing boxes at Dendy Street Beach.",
    housing: "Housing stock is diverse — heritage Victorian and Edwardian homes near Middle Brighton, mid-century Californian bungalows through the interwar streets, and larger contemporary rebuilds along Esplanade and North Road corridors. Land values are among the highest in Melbourne, which typically favours quality knockdown-rebuilds and premium renovations over subdivision.",
    overlays: "Parts of Brighton fall within a Heritage Overlay (particularly around Middle Brighton, New Street and Bay Street precincts) and a Neighbourhood Character Overlay. Any works to a covered property — including demolition, extensions and some façade changes — typically require a planning permit through Bayside City Council in addition to a building permit.",
    renovations: [
      "Full home renovations of period Edwardian, Victorian and interwar homes — often retaining street frontages while opening up the rear",
      "Kitchen and bathroom renovations in mid-century properties with dated wet areas",
      "Second-storey additions where site coverage and overlay controls allow",
      "Knockdown-rebuild new homes on established lots with generous frontages",
    ],
    lifestyle: "Family-driven area with strong demand for open-plan living, indoor-outdoor connection, and generous kitchen zones suited to entertaining. Homeowners often prioritise natural light, quality joinery and premium finishes.",
    keywords: ["home builders Brighton", "renovation builder Brighton", "kitchen renovation Brighton", "bathroom renovation Brighton", "custom home builder Brighton Bayside"],
  },
  "bentleigh-east": {
    name: "Bentleigh East", state: "VIC", postcode: "3165",
    council: "City of Glen Eira",
    zone: "General Residential Zone",
    profile: "Bentleigh East sits about 14 km south-east of the CBD and is a highly sought-after family suburb in the City of Glen Eira, popular for its access to schools, Centre Road shopping and proximity to bayside beaches.",
    housing: "The suburb is dominated by 1950s–1970s cream brick and weatherboard homes on typical 600–650m² blocks. Many have compact original kitchens, single bathrooms and separated living areas ripe for renovation. The suburb has seen a steady wave of full home renovations, rear extensions and knockdown-rebuilds over the past decade.",
    overlays: "Glen Eira Council operates under the Glen Eira Planning Scheme. Some streets are affected by Neighbourhood Character Overlays. Height, site coverage and setbacks are controlled through the Neighbourhood Residential and General Residential Zone provisions.",
    renovations: [
      "Rear open-plan extensions replacing dated kitchen/dining/family additions",
      "Second-storey additions to add bedrooms and family bathrooms",
      "Full internal renovations opening cramped 1960s layouts",
      "Knockdown-rebuild custom family homes on regular lots",
    ],
    lifestyle: "Established family suburb — buyers typically look for larger open-plan living zones, four+ bedrooms, dedicated study/home office, and quality kitchen-butler pantry configurations.",
    keywords: ["home builders Bentleigh East", "renovation builder Bentleigh East", "kitchen renovation Bentleigh East", "bathroom renovation Bentleigh East"],
  },
  bentleigh: {
    name: "Bentleigh", state: "VIC", postcode: "3204",
    council: "City of Glen Eira",
    zone: "General Residential Zone; select Neighbourhood Residential pockets",
    profile: "Bentleigh, roughly 13 km south-east of the CBD, is a busy family suburb with a well-known Centre Road shopping strip, strong public and private school options, and easy Frankston line access.",
    housing: "Housing is a mix of interwar Californian bungalows, post-war weatherboard homes and more recent townhouses. Original homes commonly have small kitchens and single bathrooms, making the suburb a hotspot for full home renovations and structural extensions.",
    overlays: "Some streets sit within Neighbourhood Character Overlays under the Glen Eira Planning Scheme. Heritage protection is limited compared to Brighton but character controls still influence facade treatment, roof form and front setbacks.",
    renovations: [
      "Kitchen renovations opening up small closed 1950s layouts",
      "Bathroom and ensuite renovations in interwar and post-war homes",
      "Rear extensions and structural additions to add family living zones",
      "Knockdown-rebuild new homes",
    ],
    lifestyle: "Popular with families and first-home upgraders; typical brief includes open-plan living, larger kitchens, dedicated laundry and outdoor entertaining area.",
    keywords: ["home builders Bentleigh", "renovation builder Bentleigh", "kitchen renovation Bentleigh", "bathroom renovation Bentleigh"],
  },
  berwick: {
    name: "Berwick", state: "VIC", postcode: "3806",
    council: "City of Casey",
    zone: "General Residential Zone; Low Density Residential pockets in the Berwick hills",
    profile: "Berwick is a well-established outer south-eastern suburb around 41 km from the Melbourne CBD, positioned around the Old Cheese Factory precinct and known for its village-style High Street, mature tree canopy and rolling hills.",
    housing: "Housing ranges from period cottages and interwar homes near Old Berwick through to large brick-veneer family homes on generous suburban lots. Newer estates around Clyde Road offer contemporary two-storey builds. The mix supports both new home builds on established or subdivided lots and full renovations on 1980s–2000s family homes.",
    overlays: "The Berwick Village precinct has Heritage Overlay controls managed by the City of Casey. Wider Berwick has no wholesale heritage protection but bushfire-prone-area and vegetation overlays may apply on the hillside fringes.",
    renovations: [
      "New home builds on existing lots and knockdown-rebuilds",
      "Second-storey additions to expand family homes",
      "Kitchen and open-plan living renovations",
      "Outdoor decking, pergolas and alfresco extensions",
    ],
    lifestyle: "Family-oriented commuter suburb with strong school and lifestyle appeal. Homeowners often prioritise four+ bedrooms, home offices, media rooms and outdoor entertaining.",
    keywords: ["new home builder Berwick", "home builders Berwick", "renovation builder Berwick", "knockdown rebuild Berwick"],
  },
  clyde: {
    name: "Clyde", state: "VIC", postcode: "3978",
    council: "City of Casey",
    zone: "Urban Growth Zone / General Residential Zone (varies by estate)",
    profile: "Clyde is a fast-growing outer south-eastern suburb about 50 km from Melbourne CBD, part of the Casey growth corridor and one of Victoria's most active new home construction areas.",
    housing: "Predominantly new master-planned estates with house-and-land packages, but demand is rising for genuinely custom new home builds where owners want architectural design, higher energy performance and premium finishes over volume-builder templates.",
    overlays: "Most Clyde parcels sit under the Casey Precinct Structure Plans and Urban Growth Zone controls. Design guidelines are commonly imposed by estate developers in addition to the standard planning framework.",
    renovations: [
      "Custom new home builds on private lots",
      "Duplex and dual-occupancy developments",
      "Extensions to earlier-generation Clyde homes as suburb matures",
    ],
    lifestyle: "Young families and first-home owners looking for four-bedroom, two-bathroom family homes with alfresco, home office, and future-proof energy efficiency.",
    keywords: ["new home builder Clyde", "custom home builder Clyde", "knockdown rebuild Clyde", "duplex builder Clyde"],
  },
  hampton: {
    name: "Hampton", state: "VIC", postcode: "3188",
    council: "Bayside City Council",
    zone: "General Residential Zone with Neighbourhood Residential Zone pockets",
    profile: "Hampton is a bayside suburb roughly 14 km south-east of Melbourne CBD, sitting between Brighton and Sandringham. It's a family-focused area with a coastal village feel around Hampton Street.",
    housing: "Housing includes heritage Californian bungalows, Edwardian and interwar homes, mid-century brick veneers and modern rebuilds. Larger renovations and knockdown-rebuilds are common on the more valuable east-west running streets.",
    overlays: "Similar to Brighton, parts of Hampton fall within Heritage Overlays and Neighbourhood Character Overlays administered by Bayside City Council. Homeowners should check the specific property overlays before planning demolition or major facade work.",
    renovations: [
      "Kitchen and bathroom renovations in Californian bungalow and Edwardian homes",
      "Rear open-plan extensions with indoor-outdoor living",
      "Full home renovations preserving heritage frontages",
      "Custom new home builds on rebuild lots",
    ],
    lifestyle: "Coastal family lifestyle. Buyers typically prioritise generous kitchen-and-living zones, quality finishes, and outdoor entertaining areas that connect to the garden.",
    keywords: ["home builders Hampton", "renovation builder Hampton", "kitchen renovation Hampton", "bathroom renovation Hampton"],
  },
  mentone: {
    name: "Mentone", state: "VIC", postcode: "3194",
    council: "City of Kingston",
    zone: "General Residential Zone",
    profile: "Mentone is a bayside suburb around 22 km south-east of Melbourne CBD, well-serviced by rail and known for its beaches, Mentone Village and strong school precinct.",
    housing: "Housing stock includes interwar Californian bungalows, post-war weatherboard homes and larger 1970s brick-veneer builds. Ongoing demand for modernising ageing homes drives strong renovation activity.",
    overlays: "The City of Kingston administers Mentone's planning. Some streets carry Neighbourhood Character Overlays. Coastal proximity means Special Building Overlays for flood/drainage may also apply on lower-lying blocks.",
    renovations: [
      "Full home renovations of ageing brick-veneer stock",
      "Kitchen and open-plan living upgrades",
      "Bathroom and ensuite renovations",
      "Second-storey additions to add bedrooms and family bathrooms",
    ],
    lifestyle: "Established family suburb with strong lifestyle appeal — homeowners often want larger family kitchens, media/rumpus rooms and outdoor decking.",
    keywords: ["home builders Mentone", "renovation builder Mentone", "kitchen renovation Mentone", "bathroom renovation Mentone"],
  },
  cheltenham: {
    name: "Cheltenham", state: "VIC", postcode: "3192",
    council: "City of Kingston",
    zone: "General Residential Zone; Commercial in Southland precinct",
    profile: "Cheltenham is a bayside-adjacent suburb about 20 km south-east of the CBD. The suburb combines residential streets with the Westfield Southland retail precinct and easy rail access.",
    housing: "A mix of post-war weatherboard and brick homes, mid-century brick veneers, and a growing wave of newer townhouses. Older homes typically have small kitchens and one bathroom, driving strong renovation demand.",
    overlays: "Kingston Planning Scheme applies. Some corridors carry design and development overlays; flood and drainage overlays may apply near lower-lying streets.",
    renovations: [
      "Bathroom renovations replacing small original wet areas",
      "Kitchen renovations opening up closed 1970s layouts",
      "Full home renovations of post-war stock",
      "Rear extensions and open-plan additions",
    ],
    lifestyle: "Popular with young families and downsizers. Modern renovations here typically focus on light-filled open-plan living, updated wet areas and outdoor entertaining.",
    keywords: ["home builders Cheltenham", "renovation builder Cheltenham", "bathroom renovation Cheltenham", "kitchen renovation Cheltenham"],
  },
  "glen-waverley": {
    name: "Glen Waverley", state: "VIC", postcode: "3150",
    council: "City of Monash",
    zone: "General Residential Zone; Activity Centre Zone at The Glen precinct",
    profile: "Glen Waverley is a major south-eastern suburb around 20 km from the CBD, home to The Glen shopping centre and consistently ranked as a top education precinct, driving strong family demand.",
    housing: "Mid-century brick veneers and 1970s–1990s two-storey brick homes on generous 600–800m² blocks dominate. Recent years have seen strong knockdown-rebuild activity, especially in the Glen Waverley Secondary College zone.",
    overlays: "Monash Planning Scheme applies. Some streets have Design and Development or Neighbourhood Character Overlays. Buyers should confirm overlays on-title before major works.",
    renovations: [
      "Custom new home builds on rebuild lots",
      "Full home renovations of 1970s–1980s stock",
      "Kitchen renovations replacing closed original layouts",
      "Second-storey additions and rear extensions",
    ],
    lifestyle: "High-value family suburb with a strong education focus. Homeowners often build four to five-bedroom homes with dedicated studies, media rooms and premium kitchen-butler layouts.",
    keywords: ["home builders Glen Waverley", "custom home builder Glen Waverley", "knockdown rebuild Glen Waverley", "kitchen renovation Glen Waverley"],
  },
};

// Resource centre articles — general Australian building knowledge (no Apollo-specific claims)
export const resourceArticles = {
  "kitchen-renovation-cost-melbourne": {
    slug: "kitchen-renovation-cost-melbourne",
    title: "Kitchen Renovation Cost in Melbourne — What to Budget in 2026",
    excerpt: "A breakdown of realistic kitchen renovation costs in Melbourne, what drives price differences, and how to plan a fixed-price project.",
    image: "",
    alt: "Modern kitchen renovation Melbourne — Apollo Builders",
    body: [
      { h: "How much does a kitchen renovation cost in Melbourne?", p: "As a general Melbourne market guide, a straightforward kitchen renovation using mid-range cabinetry, stone benchtops and standard appliances typically costs from around $30,000 to $50,000. A larger structural kitchen renovation with wall removal, new plumbing and electrical, custom cabinetry and premium appliances typically ranges from $55,000 to $90,000 or more depending on materials and complexity." },
      { h: "What drives the price?", p: "The biggest cost drivers are cabinetry linear-metreage, benchtop material (laminate vs engineered stone vs natural stone), whether walls are being moved, plumbing/electrical relocations, splashback choice, and appliance grade. Butler's pantries and integrated appliances add cost." },
      { h: "Fixed price vs cost-plus", p: "For most Melbourne homeowners a fixed-price contract offers the most certainty. The scope, inclusions and variation policy are agreed in writing before work begins. Cost-plus contracts can be appropriate for very complex renovations where scope truly cannot be pinned down." },
      { h: "Timeline expectations", p: "A typical kitchen renovation in Melbourne takes three to six weeks on-site, plus a design and lead-time period for custom cabinetry and stone that can add three to six weeks. Structural kitchens involving wall removals can take longer." },
      { h: "Getting a realistic quote", p: "Provide a written brief with your rough scope, must-have inclusions, appliance preferences and photos of the existing kitchen. Detailed on-site measure enables a fixed-price quote rather than a ballpark." },
    ],
  },
  "bathroom-renovation-timeline": {
    slug: "bathroom-renovation-timeline",
    title: "How Long Does a Bathroom Renovation Take? A Melbourne Guide",
    excerpt: "Realistic bathroom renovation timelines for Melbourne homes, from planning to hand-back.",
    image: "",
    alt: "Bathroom renovation Melbourne South-East — Apollo Builders",
    body: [
      { h: "Typical bathroom renovation timeline", p: "A standard bathroom renovation in Melbourne takes three to five weeks on-site. Larger ensuites or main bathrooms with structural changes can take five to seven weeks. Design and cabinetry lead-time adds another two to four weeks before work begins." },
      { h: "The stages", p: "Strip-out (1–2 days), rough-in plumbing/electrical (2–3 days), waterproofing to AS3740 (2–3 days with mandatory drying time), tiling (5–8 days), stone/vanity install, fit-off plumbing and electrical, final trades and clean." },
      { h: "Why waterproofing matters", p: "Under Australian Standard AS3740, wet-area waterproofing must be installed by a licensed applicator and requires drying time between coats. Cutting this short is a common source of long-term bathroom problems and insurance issues." },
      { h: "Living through it", p: "Most single-bathroom homeowners relocate for the on-site period. If a home has a second bathroom, staying put is usually feasible. Talk to your builder about dust protection and access." },
    ],
  },
  "knockdown-rebuild-melbourne": {
    slug: "knockdown-rebuild-melbourne",
    title: "Knockdown Rebuild in Melbourne — Is It Right For You?",
    excerpt: "When a knockdown-rebuild beats a renovation in Melbourne — process, cost drivers and planning considerations.",
    image: "",
    alt: "Knockdown rebuild Melbourne — Apollo Builders new home build",
    body: [
      { h: "When knockdown-rebuild makes sense", p: "A knockdown-rebuild is often the better path when the existing home has structural issues, poor layout that would be expensive to correct, low ceiling heights, asbestos or unstable stumps, or when the land value dwarfs the existing dwelling. If more than roughly 50% of the home would need replacing, a rebuild is often more economical than a full renovation." },
      { h: "Typical process", p: "Feasibility and site inspection, design and documentation, planning permit if required by overlays, building permit, demolition and services disconnect, construction, occupancy certificate, hand-over. Total programme typically six to twelve months depending on scope." },
      { h: "Planning considerations in Melbourne", p: "Most established Melbourne suburbs allow a single dwelling on an existing residential lot as-of-right, but Heritage Overlays, Neighbourhood Character Overlays and Environmental Significance Overlays can trigger a planning permit. Bushfire-prone-area controls apply on some fringe suburbs. Always check the property planning report on VicPlan before committing." },
      { h: "Fixed price contracts", p: "Because a knockdown-rebuild is a major investment, most Melbourne owners insist on a fixed-price contract with a clear scope of inclusions, variations policy and progress payment schedule." },
    ],
  },
  "choosing-a-builder-melbourne": {
    slug: "choosing-a-builder-melbourne",
    title: "Choosing a Builder in Melbourne — 8 Questions to Ask",
    excerpt: "How to shortlist a residential builder in Melbourne — the practical checks every homeowner should make.",
    image: "",
    alt: "Choosing a residential builder Melbourne — Apollo Builders",
    body: [
      { h: "1. Are they registered and insured?", p: "Domestic building work over $10,000 in Victoria must be carried out by a builder registered with the Victorian Building Authority (VBA). For work over $16,000, the builder must also provide Domestic Building Insurance (DBI) covering the client if the builder dies, disappears or becomes insolvent." },
      { h: "2. Do they offer a fixed-price contract?", p: "Fixed-price contracts provide certainty on scope and cost. Ask to see the standard contract, inclusions, exclusions and variations policy before signing." },
      { h: "3. Have they built the type of project you need?", p: "A builder experienced in kitchen renovations may not be the ideal choice for a two-storey extension. Look at recent portfolio work of similar scope and complexity." },
      { h: "4. How is communication managed?", p: "Regular walkthroughs, a single point of contact, and clear reporting through each construction stage protect your investment. Ask for the builder's communication rhythm." },
      { h: "5. Timeline and start dates", p: "Reputable builders will provide a realistic timeline before starting. A vague or highly optimistic timeline is a warning sign." },
      { h: "6. Written quotes", p: "Every serious quote should be itemised and written. Verbal 'ballpark' figures are for early conversations only." },
      { h: "7. References", p: "Ask for two or three references from recent projects and follow up. Good builders welcome this." },
      { h: "8. Cooling off and payments", p: "Under Australian domestic building law, homeowners have a five-business-day cooling-off period on major domestic building contracts. Progress payments should follow the standard construction milestones." },
    ],
  },
};
